---
joint_state_estimator:
  ros__parameters:
    type: linear_feedback_controller/JointStateEstimator
    state_interfaces:
    - ${arm_id}_joint1/position
    - ${arm_id}_joint2/position
    - ${arm_id}_joint3/position
    - ${arm_id}_joint4/position
    - ${arm_id}_joint5/position
    - ${arm_id}_joint6/position
    - ${arm_id}_joint7/position
    - ${arm_id}_joint1/velocity
    - ${arm_id}_joint2/velocity
    - ${arm_id}_joint3/velocity
    - ${arm_id}_joint4/velocity
    - ${arm_id}_joint5/velocity
    - ${arm_id}_joint6/velocity
    - ${arm_id}_joint7/velocity
    - ${arm_id}_joint1/effort
    - ${arm_id}_joint2/effort
    - ${arm_id}_joint3/effort
    - ${arm_id}_joint4/effort
    - ${arm_id}_joint5/effort
    - ${arm_id}_joint6/effort
    - ${arm_id}_joint7/effort
    command_interfaces:
    - linear_feedback_controller/${arm_id}_joint1/position
    - linear_feedback_controller/${arm_id}_joint2/position
    - linear_feedback_controller/${arm_id}_joint3/position
    - linear_feedback_controller/${arm_id}_joint4/position
    - linear_feedback_controller/${arm_id}_joint5/position
    - linear_feedback_controller/${arm_id}_joint6/position
    - linear_feedback_controller/${arm_id}_joint7/position
    - linear_feedback_controller/${arm_id}_joint1/velocity
    - linear_feedback_controller/${arm_id}_joint2/velocity
    - linear_feedback_controller/${arm_id}_joint3/velocity
    - linear_feedback_controller/${arm_id}_joint4/velocity
    - linear_feedback_controller/${arm_id}_joint5/velocity
    - linear_feedback_controller/${arm_id}_joint6/velocity
    - linear_feedback_controller/${arm_id}_joint7/velocity
    - linear_feedback_controller/${arm_id}_joint1/effort
    - linear_feedback_controller/${arm_id}_joint2/effort
    - linear_feedback_controller/${arm_id}_joint3/effort
    - linear_feedback_controller/${arm_id}_joint4/effort
    - linear_feedback_controller/${arm_id}_joint5/effort
    - linear_feedback_controller/${arm_id}_joint6/effort
    - linear_feedback_controller/${arm_id}_joint7/effort

linear_feedback_controller:
  ros__parameters:
    type: linear_feedback_controller/LinearFeedbackController
    moving_joint_names:
    - ${arm_id}_joint1
    - ${arm_id}_joint2
    - ${arm_id}_joint3
    - ${arm_id}_joint4
    - ${arm_id}_joint5
    - ${arm_id}_joint6
    - ${arm_id}_joint7
    ${arm_id}_joint1:
      p: 1000.0
      d: 5.0
    ${arm_id}_joint2:
      p: 1000.0
      d: 5.0
    ${arm_id}_joint3:
      p: 1000.0
      d: 5.0
    ${arm_id}_joint4:
      p: 1000.0
      d: 2.0
    ${arm_id}_joint5:
      p: 20.0
      d: 2.0
    ${arm_id}_joint6:
      p: 10.0
      d: 2.0
    ${arm_id}_joint7:
      p: 5.0
      d: 1.0
    chainable_controller:
      command_interfaces:
      - ${arm_id}_joint1/effort
      - ${arm_id}_joint2/effort
      - ${arm_id}_joint3/effort
      - ${arm_id}_joint4/effort
      - ${arm_id}_joint5/effort
      - ${arm_id}_joint6/effort
      - ${arm_id}_joint7/effort
      re${arm_id}ence_prefix: ''
    joint_velocity_filter_coefficient: 0.9
    pd_to_lf_transition_duration: 0.1
    remove_gravity_compensation_effort: true
    robot_has_free_flyer: false
