robot:
  name :  "panda"
  world_frame_name : "universe"
  start_pose : "np.array([-np.pi/2, -1, 0, -2.5, 0.0, 2, 0.0, 0.0, 0.0])"
  tool_frame_name : "panda_hand_tcp"
MPC:
  dt :  0.01 # time is in seconds
  total_time : 30
  nb_steps_horizon : 100
  max_nb_iter : 1
  solver:
    tolerance : 1e-7
    rollout_type : aligator.ROLLOUT_LINEAR
    sa_strategy : aligator.SA_LINESEARCH_NONMONOTONE
    linear_solver_choice : aligator.LQ_SOLVER_PARALLEL
    num_threads : 10
    mu_init : 1e-7  # penalite sur les contraintes
  weights:
    regulation:
      stage_joint : 1e-2 #1e-4
      stage_vel : 1e-1 # 1e-2
      command : 2e-1 # 1e-2
      term_state : 1e-30
    waypoints:
      frame_pos : 100
      frame_vel : 1
      orientation : 1
    collision : 0.1 # very sensitive, max around ~ 0.1

trajectory:
  tool_orientation : "np.array([np.pi, 0., 0.])"
  velocity :
    spread : 0.1
    start : 0.1
